[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[MathLink]]
deps = ["Libdl", "Printf"]
git-tree-sha1 = "456465e96317c706dc2e782f441bff3053ff843e"
uuid = "18c93696-a329-5786-9845-8443133fa0b4"
version = "0.3.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
